language: rust
env:
  - DATABASE_URL=postgres://localhost/boilerplateapp
services:
  - postgresql
rust:
  - nightly
matrix:
  allow_failures:
    - rust: [stable, beta]
before_script:
  - cargo install diesel_cli
  - ./reset.sh
