language: rust
cache: cargo
env:
  - DATABASE_URL=postgres://localhost/boilerplateapp
services:
  - postgresql
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta

before_script:
  - cargo install --force diesel_cli
  - cp .env.example .env
  - ./reset.sh
script:
  - bash -c '[[ "TRAVIS_RUST_VERSION" == "nightly" ]] && cargo build --features "strict clippy" || cargo build'
  - cargo test --verbose
