language: rust
env:
  - DATABASE_URL=postgres://localhost/boilerplateapp
services:
  - postgresql
rust:
  - nightly
matrix:
  allow_failures:
    - rust: [stable, beta]
before_script:
  - cargo install diesel_cli
  - ./reset.sh
script:
  - [[ "TRAVIS_RUST_VERSION" == "nightly" ]] && cargo build --verbose || cargo build --verbose --features clippy
  - cargo test --verbose
