language: rust
env:
  - BOILERPLATEAPP_DATABASE_URL=postgres://localhost/boilerplateapp
services:
  - postgresql
rust:
  - nightly
matrix:
  allow_failures:
    - rust: [stable, beta]
before_script:
  - cargo install diesel_cli
  - ./reset.sh
script:
  - bash -c '[[ "TRAVIS_RUST_VERSION" == "nightly" ]] && cargo build --features "strict clippy" || cargo build'
  - cargo test --verbose
